development:
  host: localhost
  driver: mysql
  database: etrates-16sep2016
  username: etrates
  password: enChantingP
  collation: utf8_unicode_ci
  charset: utf8
  timeout: 10000
  prefix: ''

production:
  host: localhost
  driver: mysql
  charset: utf8
  database: rates
  collation: utf8_unicode_ci
  username: builder
  password: 'tr@velm@ker'
  timeout: 10000
  prefix: ''
  # port: 3306
