<?php

/*
  Project                     : Oriole
  Module                      :
  File name                   : errorcodes.php
  Description                 : Contains Error codes used in Oriole Project
  Copyright                   : Copyright © 2014, Audvisor Inc.
                                Written under contract by Robosoft Technologies Pvt. Ltd.
  History                     :
 */
define("ERRCODE_NO_ERROR", 0);

define("ERRCODE_CONSUMER_API_INSUFFICIENT_PARAM", 100);
define("ERRCODE_EMAIL_ID_EXISTS", 101);
define("ERRCODE_INVALID_REFERRAL_ID", 102);
define("ERRCODE_CONSUMER_INVALID_JSON", 103);
define("SERVER_EXCEPTION_UNKNOWN_ERROR", 104);
define("ERRCODE_SERVER_EXCEPTION_STATIONS", 105);
define("ERRCODE_EMPTY_ARRAY", 106);
define("ERRCODE_POSTDATA_ERROR", 107);
define("ERRCODE_EMAIL_NOT_FOUND", 108);
define("ERRCODE_FIELD_EMPTY", 109);
define("ERRCODE_SERVER_EXCEPTION_GET_TOPIC", 110);
define("ERRCODE_SERVER_EXCEPTION_GET_EXPERT", 111);
define("ERRCODE_SERVER_EXCEPTION_GET_INSIGHT", 112);
define("ERRCODE_SERVER_EXCEPTION_GET_STREAMING_URL", 113);
define("ERRCODE_DEVICE_REGISTERED", 114);
define("ERRCODE_HASHED_PASSWORD_NULL", 115);
define("ERRCODE_PASSWORD_DOESNT_MATCH", 116);
define("ERROR_CODE_INVALID_INSIGHT_ID", 117);
define("ERROR_CODE_INVALID_RECEIVER_ID", 118);
define("ERROR_CODE_INVALID_RECEIVER_TYPE", 119);
define("ERROR_CODE_LINK_EXPIRED", 121);
define("ERRCODE_EMAIL_NOT_SENT", 120);
define("ERRCODE_INVALID_JSON", 125);
define("ERRCODE_INVALID_CLIENT_ID", 126);
define("ERRCODE_INVALID_AUTH_ID", 127);
define("ERRCODE_USER_LIMIT_EXCEEDED", 128);

define("ERRCODE_SERVER_EXCEPTION_STATION_TYPE", 201);
define("ERRCODE_SERVER_EXCEPTION_DEL_TOPIC", 202);
define("SERVER_EXCEPTION_DEL_TOPIC", 203);
define("ERRCODE_SERVER_EXCEPTION_DEL_EXPERT", 205);
define("SERVER_EXCEPTION_DEL_EXPERT", 206);
define("ERRCODE_SERVER_EXCEPTION_GET_VERSION", 207);
define("ERRCODE_INVALID_CONSUMER", 208);
define("ERRCODE_SERVER_EXCEPTION_GET_USER_ACTIONS", 209);
define("ERRCODE_SERVER_EXCEPTION_UNSUPPORTED_API", 210);
define("ERROR_CODE_INVALID_PASSWORD", 213);
define("ERRCODE_INVALID_PLATFORM", 215);

define("ERRCODE_SERVER_EXCEPTION_EDIT_TOPIC", 320);
define("SERVER_EXCEPTION_NO_FAVOURITES", 321);
define("ERROR_CODE_INSIGHT_NOT_AVAILABLE", 322);
define("ERROR_CODE_INSIGHT_INSERT_FAIL", 323);
define("ERROR_CODE_INSIGHT_NOT_DELETED", 324);
define("ERRCODE_INVALID_STREAMING_URL", 325);
define("ERRCODE_INSIGHT_VOICEOVER_UPLOAD_FAILED", 255);

define("ERRCODE_INSIGHT", 405);
define("ERRCODE_CONSUMER", 406);

define("ERRCODE_INVALID_CHANNEL", 500);
define("ERROR_CODE_FAVOURITE_EXISTS", 212);
define("ERROR_CODE_SERVER_COMMUNICATION_FAILED", 510);
define("ERROR_CODE_INVALID_PROMO_CODE", 407);
define("ERROR_CODE_PROMO_CODE_EXPIRED", 408);
define("ERRCODE_SERVER_EXCEPTION_GET_PROMOCODE", 326);

define("SUBSCRIPTION_EXPIRED_ERROR_CODE", 327);
define("ERRCODE_INVALID_FEATURED_INSIGHT_COUNT_ERROR", 328);
define("ERRCODE_TAG_WP_URL_INCORRECT", 329);
