#!/bin/bash
echo "Deployment begin"

echo "Stopping Nginx"
sudo service nginx stop

echo "Stopping PHP"
sudo service php5-fpm stop

echo "Changing CWD to Engine root"
pushd /home/ubuntu/CoreEngineRoom

echo "Review code before update"
git status

read -p "Press any key to continue... " -n1 -s

echo "Discarding local changes"
git reset --hard

echo "Review code before update"
git fetch
git status
read -p "Press any key to continue... " -n1 -s

echo "Updating code"
git pull --rebase

echo "Patching Config"

defaultOption=0
while true; do
    if [ "$defaultOption" -eq 0 ]; then
        echo "Enter \"1\" for Stage, \"2\" for Loading Bay or \"3\" for API Server: "
        read response
    fi

    case $response
    in
        1) echo "Patching as stage"
        mv /home/ubuntu/CoreEngineRoom/src/config/config_stage.php /home/ubuntu/CoreEngineRoom/src/config/config.php 
        break
        ;;
        2) echo "Patching as Loading Bay"
        mv /home/ubuntu/CoreEngineRoom/src/config/config_dock.php /home/ubuntu/CoreEngineRoom/src/config/config.php
        break
        ;;
        3) echo "Patching as API server" 
        mv /home/ubuntu/CoreEngineRoom/src/config/config_engine.php /home/ubuntu/CoreEngineRoom/src/config/config.php
        echo "Enabling health beacon."
        echo "<html><body>iamok</body></html>" >> /home/ubuntu/CoreEngineRoom/ruok.html
        break
        ;;
        *) echo "Patch as $AUD_SERVER?"
        read  confirmPatch
        case $AUD_SERVER
            in
            "API") 
            defaultOption=1
            response=3 
            ;;
            "DOCK")
            defaultOption=1
            response=2 
            ;;
            "STAGE") 
            defaultOption=1
            response=1 
            ;;
            *)
        esac
    esac
done


read -p "Setup the Config.php and Press any key to continue... " -n1 -s

echo "Run Composer Install"
/home/ubuntu/CoreEngineRoom/Composer_Install.command

echo "Updating Nginx configuration"
#TODO

echo "Restoring the CWD"
popd

echo "Restarting PHP"
sudo service php5-fpm start

echo "Restarting Nginx"
sudo service nginx start

echo "Deployment complete"
